<?php
/*
 * All The fonts.
 */
$fonts_data = array(	
	array( 'name' => "Arial", 'variant' => '', 'source' => 'system', 'faces' => 'Helvetica, sans-serif'),
	array( 'name' => "Courier New", 'variant' => '', 'source' => 'system', 'faces' => 'monospace'),
	array( 'name' => "Georgia", 'variant' => '', 'source' => 'system', 'faces' => 'serif'),
	array( 'name' => "Lucida Sans Unicode", 'variant' => '', 'source' => 'system', 'faces' => '"Lucida Grande", sans-serif'),
	array( 'name' => "Tahoma", 'variant' => '', 'source' => 'system', 'faces' => 'Geneva, sans-serif'),
	array( 'name' => "Times New Roman", 'variant' => '', 'source' => 'system', 'faces' => 'Times, serif'),
	array( 'name' => "Trebuchet MS", 'variant' => '', 'source' => 'system', 'faces' => 'Geneva, sans-serif'),
	array( 'name' => "Verdana", 'variant' => '', 'source' => 'system', 'faces' => 'Geneva, sans-serif'),
	array( 'name' => "Cantarell", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Cardo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Crimson Text", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Droid Sans", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Droid Sans Mono", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Droid Serif", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "IM Fell DW Pica", 'variant' => ':r,i', 'source' => 'google'),
	array( 'name' => "Inconsolata", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Josefin Sans", 'variant' => ':400,400italic,700,700italic', 'source' => 'google'),
	array( 'name' => "Josefin Slab", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Lobster", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Molengo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nobile", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "OFL Sorts Mill Goudy TT", 'variant' => ':r,i', 'source' => 'google'),
	array( 'name' => "Old Standard TT", 'variant' => ':r,b,i', 'source' => 'google'),
	array( 'name' => "Reenie Beanie", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Tangerine", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Vollkorn", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Yanone Kaffeesatz", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Cuprum", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Neucha", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Neuton", 'variant' => '', 'source' => 'google'),
	array( 'name' => "PT Sans", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "PT Sans Caption", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "PT Sans Narrow", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Philosopher", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Allerta", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Allerta Stencil", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Arimo", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Arvo", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Bentham", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Coda", 'variant' => ':800', 'source' => 'google'),
	array( 'name' => "Cousine", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Covered By Your Grace", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Geo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Just Me Again Down Here", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Puritan", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Raleway", 'variant' => ':100', 'source' => 'google'),
	array( 'name' => "Raleway Dots", 'variant' => ':400', 'source' => 'google'),	
	array( 'name' => "Tinos", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "UnifrakturCook", 'variant' => ':bold', 'source' => 'google'),
	array( 'name' => "UnifrakturMaguntia", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Mountains of Christmas", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Lato", 'variant' => ':400,700,400italic', 'source' => 'google'),
	array( 'name' => "Orbitron", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Allan", 'variant' => ':bold', 'source' => 'google'),
	array( 'name' => "Anonymous Pro", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Copse", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Kenia", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Ubuntu", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Vibur", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sniglet", 'variant' => ':800', 'source' => 'google'),
	array( 'name' => "Syncopate", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Cabin", 'variant' => ':400,400italic,700,700italic,', 'source' => 'google'),
	array( 'name' => "Merriweather", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Maiden Orange", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Just Another Hand", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Kristi", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Gruppo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Buda", 'variant' => ':light', 'source' => 'google'),
	array( 'name' => "Lekton", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Luckiest Guy", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Crushed", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Chewy", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Coming Soon", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Crafty Girls", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Fontdiner Swanky", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Permanent Marker", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rock Salt", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sunshiney", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Unkempt", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Calligraffitti", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Cherry Cream Soda", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Homemade Apple", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Irish Growler", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Kranky", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Schoolbell", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Slackey", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Walter Turncoat", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Radley", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Meddon", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Kreon", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Dancing Script", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Goudy Bookletter 1911", 'variant' => '', 'source' => 'google'),
	array( 'name' => "PT Serif Caption", 'variant' => ':r,i', 'source' => 'google'),
	array( 'name' => "PT Serif", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Astloch", 'variant' => ':b', 'source' => 'google'),
	array( 'name' => "Bevan", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Anton", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Expletus Sans", 'variant' => ':b', 'source' => 'google'),
	array( 'name' => "VT323", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Pacifico", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Candal", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Architects Daughter", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Indie Flower", 'variant' => '', 'source' => 'google'),
	array( 'name' => "League Script", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Quattrocento", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Amaranth", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Irish Grover", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Oswald", 'variant' => ':400,300,700', 'source' => 'google'),
	array( 'name' => "EB Garamond", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Round", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Slim", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Script", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Cut", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Mono", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Oval", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nova Flat", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Terminal Dosis Light", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Michroma", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Miltonian", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Miltonian Tattoo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Annie Use Your Telescope", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Dawning of a New Day", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sue Ellen Francisco", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Waiting for the Sunrise", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Special Elite", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Quattrocento Sans", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Smythe", 'variant' => '', 'source' => 'google'),
	array( 'name' => "The Girl Next Door", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Aclonica", 'variant' => '', 'source' => 'google'),
	array( 'name' => "News Cycle", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Damion", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Wallpoet", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Over the Rainbow", 'variant' => '', 'source' => 'google'),
	array( 'name' => "MedievalSharp", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Six Caps", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Swanky and Moo Moo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Bigshot One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Francois One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sigmar One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Carter One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Holtwood One SC", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Paytone One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Monofett", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rokkitt", 'variant' => ':400,700', 'source' => 'google'),
	array( 'name' => "Megrim", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Judson", 'variant' => ':r,ri,b', 'source' => 'google'),
	array( 'name' => "Didact Gothic", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Play", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Ultra", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Metrophobic", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Mako", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Shanti", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Caudex", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Jura", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Ruslan Display", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Brawler", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nunito", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Wire One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Podkova", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Muli", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Maven Pro", 'variant' => ':400,500,700', 'source' => 'google'),
	array( 'name' => "Tenor Sans", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Limelight", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Playfair Display", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Artifika", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Lora", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Kameron", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Cedarville Cursive", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Zeyada", 'variant' => '', 'source' => 'google'),
	array( 'name' => "La Belle Aurore", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Shadows Into Light", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Lobster Two", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Nixie One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Redressed", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Bangers", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Open Sans Condensed", 'variant' => ':300,300italic', 'source' => 'google'),
	array( 'name' => "Open Sans", 'variant' => ':r,i,b,bi', 'source' => 'google'),
	array( 'name' => "Varela", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Goblin One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Asset", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Gravitas One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Hammersmith One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Stardos Stencil", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Love Ya Like A Sister", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Loved by the King", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Bowlby One SC", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Forum", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Patrick Hand", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Varela Round", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Yeseva One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Give You Glory", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Modern Antiqua", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Bowlby One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Tienne", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Istok Web", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Yellowtail", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Pompiere", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Unna", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rosario", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Leckerli One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Snippet", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Ovo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "IM Fell English", 'variant' => ':r,i', 'source' => 'google'),
	array( 'name' => "IM Fell English SC", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Gloria Hallelujah", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Kelly Slab", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Black Ops One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Carme", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Aubrey", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Federo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Delius", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rochester", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rationale", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Abel", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Marvel", 'variant' => ':r,b,i,bi', 'source' => 'google'),
	array( 'name' => "Actor", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Delius Swash Caps", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Smokum", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Tulpen One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Coustard", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Andika", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Alice", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Questrial", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Comfortaa", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Geostar", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Geostar Fill", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Volkhov", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Voltaire", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Montez", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Short Stack", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Vidaloka", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Aldrich", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Numans", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Days One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Gentium Book Basic", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Monoton", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Alike", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Delius Unicase", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Abril Fatface", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Dorsa", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Antic", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Passero One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Fanwood Text", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Prociono", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Merienda One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Changa One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Julee", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Prata", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Adamina", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sorts Mill Goudy", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Terminal Dosis", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sansita One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Chivo", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Spinnaker", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Poller One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Alike Angular", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Gochi Hand", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Poly", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Andada", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Federant", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Ubuntu Condensed", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Ubuntu Mono", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Sancreek", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Coda", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rancho", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Satisfy", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Pinyon Script", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Vast Shadow", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Marck Script", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Salsa", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Amatic SC", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Quicksand", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Linden Hill", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Corben", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Creepster Caps", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Butcherman Caps", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Eater Caps", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Nosifer Caps", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Atomic Age", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Contrail One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Jockey One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Cabin Sketch", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Cabin Condensed", 'variant' => ':r,b', 'source' => 'google'),
	array( 'name' => "Fjord One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Rametto One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Mate", 'variant' => ':r,i', 'source' => 'google'),
	array( 'name' => "Mate SC", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Arapey", 'variant' => ':r,i', 'source' => 'google'),
	array( 'name' => "Supermercado One", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Petrona", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Lancelot", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Convergence", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Cutive", 'variant' => '', 'source' => 'google'),
	array( 'name' => "Karla", 'variant' => ':400,400italic,700,700italic', 'source' => 'google')					
);